## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

before_script:
 - if [ $TRAVIS_OS_NAME = linux ]; then
     echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main' | sudo tee /etc/apt/sources.list.d/realsense-public.list;
     sudo apt-key adv --keyserver keys.gnupg.net --recv-key 6F3EFCDE;
     sudo apt-get update -qq;
     sudo apt-get install linux-headers-$(uname -r) -y;
     sudo apt-get install librealsense2-dkms -y;
     sudo apt-get install librealsense2-utils -y;
     sudo apt-get install librealsense2-dev -y;
   fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("RealSense"); Pkg.test("RealSense"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("RealSense")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("RealSense")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
