# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true
notifications:
  email: false
before_install:
  - powershell (new-object net.webclient).DownloadFile("https://github.com/IntelRealSense/librealsense/releases/download/v2.32.1/Intel.RealSense.SDK-WIN10-2.32.1.1297.exe", "C:\projects\Intel.RealSense.SDK.exe")
  - C:\projects\Intel.RealSense.SDK.exe /SILENT
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
